"""add description to recipe

Revision ID: 2515b32102b9
Revises: 4dc895760185
Create Date: 2025-12-26 01:52:41.269520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2515b32102b9'
down_revision: Union[str, Sequence[str], None] = '4dc895760185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('description', sa.String(), nullable=False, server_default='No description provided'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'description')
    # ### end Alembic commands ###
