"""fix ai suggestion import

Revision ID: 5080a47ea891
Revises: 
Create Date: 2025-12-25 22:58:24.885645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5080a47ea891'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_suggestions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ingredients', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('suggestion_text', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cuisine', sa.String(), nullable=False),
    sa.Column('isVegetarian', sa.Boolean(), nullable=True),
    sa.Column('prepTimeMinutes', sa.Integer(), nullable=False),
    sa.Column('ingredients', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipes')
    op.drop_table('ai_suggestions')
    # ### end Alembic commands ###
